name: Build and Push to ECR

on:
  workflow_dispatch:

env:
  ECR_REPOSITORY: lab3_ecr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # ========================================
      # 1. Checkout
      # ========================================
      - name: Checkout code
        uses: actions/checkout@v4

      # ========================================
      # 2. Configure AWS using OIDC
      # ========================================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: <ARN Role>
          aws-region: 'ap-southeast-1'

      # ========================================
      # 3. Login to ECR
      # ========================================
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ========================================
      # 4. Build Backend
      # ========================================
      - name: Build Backend Image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }} \
            ./fastapi-backend

      # ========================================
      # 5. Build Frontend
      # ========================================
      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ vars.VITE_API_URL }} \
            --build-arg VITE_DEV_API_TARGET=${{ vars.VITE_DEV_API_TARGET }} \
            --build-arg VITE_GOOGLE_CLIENT_ID=${{ vars.VITE_GOOGLE_CLIENT_ID }} \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }} \
            ./frontend

      # ========================================
      # 6. Push Backend
      # ========================================
      - name: Push Backend Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }}

      # ========================================
      # 7. Push Frontend
      # ========================================
      - name: Push Frontend Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }}

      # ========================================
      # 8. Show images
      # ========================================
      - name: Deployment Information
        run: |
          echo "Backend:"
          echo "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }}"

          echo "Frontend:"
          echo "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }}"